export const heroVisualStyles = {
  stage: 'relative mx-auto aspect-[10/9] w-full max-w-lg lg:col-span-5 lg:aspect-square lg:max-w-none',
  ringLarge: 'absolute -end-10 -top-8 size-64 rounded-full border border-sand-200',
  ringSmall: 'absolute start-4 bottom-2 size-24 rounded-full bg-sand-100',

  card: 'absolute end-0 top-4 aspect-[1.586] w-[82%] -rotate-3 overflow-hidden rounded-2xl bg-brand-600 p-5 text-white shadow-sm md:p-7',
  cardCircleA: 'absolute -start-16 -bottom-20 size-56 rounded-full border border-white/15',
  cardCircleB: 'absolute -start-6 -bottom-10 size-36 rounded-full border border-white/10',
  cardTop: 'relative flex items-center justify-between',
  cardBank: 'text-lg font-bold md:text-xl',
  contactless: 'rotate-90 opacity-80',
  chip: 'relative mt-6 block h-8 w-11 rounded-md bg-sand-200 md:mt-8 md:h-9 md:w-12',
  cardBottom: 'absolute inset-x-5 bottom-5 md:inset-x-7 md:bottom-6',
  cardNumber: 'tabular block text-start text-base tracking-[0.18em] md:text-lg',
  cardMeta: 'mt-2 flex items-center justify-between text-xs text-brand-100 md:text-sm',

  activity: 'absolute start-0 bottom-0 w-[64%] rounded-xl border border-line bg-surface p-4 shadow-sm md:p-5',
  activityTitle: 'text-sm font-semibold text-ink',
  activityList: 'mt-3 space-y-3',
  activityItem: 'flex items-center gap-3',
  activityIcon: 'inline-flex size-9 shrink-0 items-center justify-center rounded-lg bg-brand-50 text-brand-600',
  activityText: 'flex min-w-0 flex-1 flex-col',
  activityLabel: 'truncate text-sm font-medium text-ink',
  activityMeta: 'truncate text-xs text-muted',
  activityAmount: 'tabular shrink-0 text-sm font-semibold',
  amountIn: 'text-success',
  amountOut: 'text-ink',
} as const
