export const homeHeroStyles = {
  section: 'relative overflow-hidden border-b border-line bg-ink',
  photo: 'absolute inset-0',
  image: 'size-full object-cover opacity-45',
  pattern: 'pointer-events-none absolute inset-0 text-white/12',
  veil: 'absolute inset-0 bg-ink/55',
  inner: 'relative z-10 pt-12 pb-16 md:pt-20 md:pb-28',
  grid: 'grid items-center gap-10 lg:grid-cols-12 lg:gap-10',
  copy: 'lg:col-span-6',
  eyebrow: 'text-[13px] font-semibold tracking-[0.18em] text-brand-300',
  title: 'mt-4 text-[28px] leading-[1.25] font-bold text-white md:text-[52px] xl:text-[60px]',
  lead: 'mt-4 max-w-md text-[16px] leading-[1.8] text-white/75 md:mt-5 md:text-lg',
  actions: 'mt-8 flex flex-wrap gap-3',
  trust: 'mt-6 flex items-center gap-2 text-[15px] font-medium text-white/70',
  trustIcon: 'shrink-0 text-brand-300',
  cardLink: 'mt-6 text-white hover:text-brand-300',
  visual: 'lg:col-span-6',
  caption:
    'relative z-10 mt-12 flex flex-wrap items-baseline justify-between gap-x-4 text-[13px] text-white/50',
} as const
