export const ctaBannerStyles = {
  section: 'relative overflow-hidden bg-ink py-20 md:py-28',
  pattern: 'pointer-events-none absolute inset-0 text-white/8',
  grid: 'relative z-10 grid items-end gap-12 lg:grid-cols-12 lg:gap-16',
  copy: 'lg:col-span-7',
  rule: 'mb-6 block h-10 w-px bg-brand-500',
  title: 'max-w-xl text-[28px] leading-[1.3] font-bold text-white md:text-[40px]',
  description: 'mt-5 max-w-md text-[17px] leading-[1.8] text-white/70 md:text-lg',
  actions: 'mt-10 flex flex-wrap items-center gap-x-6 gap-y-3',
  secondary: 'text-white hover:text-brand-300',
  media: 'lg:col-span-5',
  frame: 'aspect-[4/5] overflow-hidden bg-brand-900',
  image: 'size-full object-cover',
  caption: 'mt-3 flex flex-wrap items-baseline justify-between gap-x-4 text-[13px] text-white/45',
} as const
