export const footerStyles = {
  footer: 'border-t border-line bg-surface text-sm',
  top: 'grid gap-12 py-14 md:py-16 lg:grid-cols-12 lg:gap-10',
  brand: 'lg:col-span-4',
  description: 'mt-5 max-w-sm leading-[1.8] text-body',
  contactList: 'mt-6 space-y-3',
  contactItem: 'flex items-start gap-2.5 text-body transition-colors duration-200 hover:text-brand-700',
  contactIcon: 'mt-0.5 shrink-0 text-brand-600',
  groups: 'grid grid-cols-2 gap-8 sm:grid-cols-4 lg:col-span-8',
  groupTitle: 'text-[15px] font-semibold text-ink',
  groupList: 'mt-4 space-y-1',
  groupLink: 'inline-flex min-h-9 items-center text-muted transition-colors duration-200 hover:text-brand-700',
  legal: 'grid gap-6 border-t border-line py-8 lg:grid-cols-12 lg:items-center',
  regulator: 'max-w-2xl leading-[1.8] text-body lg:col-span-7',
  legalFacts: 'flex flex-wrap gap-x-8 gap-y-3 lg:col-span-5 lg:justify-end',
  legalFact: 'flex gap-2 text-muted [&>dd]:font-medium [&>dd]:text-ink',
  bottom: 'flex flex-col gap-4 border-t border-line py-6 text-muted md:flex-row md:items-center md:justify-between',
  bottomLinks: 'flex flex-wrap gap-x-6 gap-y-2',
  bottomLink: 'inline-flex min-h-9 items-center transition-colors duration-200 hover:text-brand-700',
} as const
