export const visaCardsStyles = {
  track: 'relative scroll-mt-[calc(4.5rem+10px)] bg-ink',
  tall: 'h-[400vh]',
  pin: 'sticky top-[calc(4.5rem+10px)] flex min-h-[calc(100svh-4.5rem-10px)] flex-col justify-center py-6 lg:py-12',
  staticPin: 'relative overflow-hidden py-16 md:py-24',
  reducedGrid: 'mt-12 grid gap-8 md:grid-cols-2',
  reducedItem: 'space-y-5',
  reducedScene: 'relative aspect-[86/54] w-full overflow-hidden',
  pattern: 'pointer-events-none absolute inset-0 text-white/10',
  inner: 'relative z-10',
  layout: 'relative z-10 grid items-center gap-5 lg:grid-cols-12 lg:gap-16',
  copy: 'order-2 min-w-0 text-center lg:order-1 lg:col-span-6 lg:text-start',
  eyebrow: 'text-[11px] font-semibold tracking-[0.14em] text-brand-300 md:text-[13px] md:tracking-[0.18em]',
  title: 'mt-1.5 text-[22px] leading-[1.3] font-bold text-white md:mt-3 md:text-[40px]',
  lead: 'mx-auto mt-3 hidden max-w-xl text-[17px] leading-[1.8] text-white/72 lg:mx-0 lg:mt-4 lg:block',
  cardName: 'mt-3 text-base font-semibold text-white md:mt-6 md:text-xl',
  cardTag: 'mt-1 text-[13px] text-brand-300 md:mt-2 md:text-[15px]',
  cardText: 'mx-auto mt-3 hidden max-w-xl text-[16px] leading-[1.8] text-white/72 lg:mx-0 lg:block',
  facts: 'mt-8 hidden gap-4 sm:grid-cols-3 lg:grid',
  fact: 'border-s-2 border-brand-500 ps-3 text-start',
  factValue: 'text-[15px] font-semibold text-white',
  factLabel: 'mt-1 text-[13px] text-white/55',
  highlights: 'mt-8 hidden space-y-2 lg:block',
  highlight: 'text-[15px] text-white/80',
  actions: 'mt-4 flex flex-wrap items-center justify-center gap-3 md:mt-8 md:gap-4 lg:justify-start',
  sample: 'hidden text-[13px] text-white/45 lg:block',
  stage: 'order-1 mx-auto w-full max-w-[340px] md:max-w-[400px] lg:order-2 lg:mx-0 lg:max-w-none lg:col-span-6',
  scene: 'relative mx-auto w-full [perspective:1400px]',
  deck: 'relative aspect-[86/54] w-full overflow-hidden',
  progress: 'mt-3 flex items-center justify-center gap-3 md:mt-8',
  progressLabel: 'text-[13px] text-white/50',
  dots: 'flex items-center gap-2',
  dot: 'size-2.5 rounded-full bg-white/25',
  dotActive: 'bg-brand-500',
} as const
