import type { VisaCardTone } from '../../../../types/home.types'

export const visaCardsStyles = {
  track: 'relative bg-ink',
  tall: 'h-[400vh]',
  pin: 'sticky top-0 flex min-h-svh flex-col justify-center overflow-hidden py-20 md:py-24',
  staticPin: 'relative overflow-hidden py-20 md:py-24',
  reducedGrid: 'mt-12 grid gap-8 md:grid-cols-2',
  reducedItem: 'space-y-5',
  reducedScene: 'relative aspect-[86/54] w-full',
  pattern: 'pointer-events-none absolute inset-0 text-white/10',
  inner: 'relative z-10',
  layout: 'relative z-10 grid items-center gap-12 lg:grid-cols-12 lg:gap-16',
  copy: 'lg:col-span-6',
  eyebrow: 'text-[13px] font-semibold tracking-[0.18em] text-brand-300',
  title: 'mt-3 text-[28px] leading-[1.3] font-bold text-white md:text-[40px]',
  lead: 'mt-4 max-w-xl text-[17px] leading-[1.8] text-white/72',
  cardName: 'mt-8 text-xl font-semibold text-white',
  cardTag: 'mt-2 text-[15px] text-brand-300',
  cardText: 'mt-3 max-w-xl text-[16px] leading-[1.8] text-white/72',
  facts: 'mt-8 grid gap-4 sm:grid-cols-3',
  fact: 'border-s-2 border-brand-500 ps-3',
  factValue: 'text-[15px] font-semibold text-white',
  factLabel: 'mt-1 text-[13px] text-white/55',
  highlights: 'mt-8 space-y-2',
  highlight: 'text-[15px] text-white/80',
  actions: 'mt-8 flex flex-wrap items-center gap-4',
  sample: 'text-[13px] text-white/45',
  stage: 'lg:col-span-6',
  scene: 'relative mx-auto w-full max-w-[420px] [perspective:1400px]',
  deck: 'relative aspect-[86/54] w-full',
  progress: 'mt-8 flex items-center justify-center gap-3',
  progressLabel: 'text-[13px] text-white/50',
  dots: 'flex items-center gap-2',
  dot: 'size-2.5 rounded-full bg-white/25',
  dotActive: 'bg-brand-500',
} as const

export const visaFaceStyles = {
  card: 'absolute inset-0 flex flex-col justify-between rounded-2xl border p-6 shadow-sm [backface-visibility:hidden] [transform-style:preserve-3d] md:p-7',
  motion: 'origin-center transition-[transform,opacity] duration-500 ease-out-soft motion-reduce:transition-none',
  active: 'z-10 opacity-100 [transform:rotateY(0deg)]',
  passed: 'z-0 opacity-0 [transform:rotateY(-80deg)]',
  next: 'z-0 opacity-0 [transform:rotateY(80deg)]',
  tone: {
    classic: 'border-brand-700 bg-brand-900 text-white',
    gold: 'border-sand-200 bg-sand-100 text-ink',
    travel: 'border-brand-700 bg-ink text-white',
    business: 'border-brand-500 bg-brand-700 text-white',
  } satisfies Record<VisaCardTone, string>,
  top: 'flex items-start justify-between gap-4',
  brand: 'text-[15px] font-semibold',
  network: 'text-sm font-bold tracking-[0.2em] uppercase',
  chipRow: 'mt-8 flex items-center gap-3',
  chip: 'relative h-9 w-12 overflow-hidden rounded-md border border-current/25 bg-current/15',
  chipLines: 'absolute inset-1 grid grid-cols-3 grid-rows-2 gap-px opacity-50',
  chipCell: 'rounded-[1px] bg-current',
  waves: 'h-5 w-5 opacity-55',
  number: 'mt-7 font-mono text-[17px] tracking-[0.18em] md:text-xl',
  meta: 'mt-6 flex items-end justify-between gap-4 text-[12px]',
  metaLabel: 'opacity-60',
  metaValue: 'mt-1 font-semibold tracking-wide',
  ornament: 'pointer-events-none absolute end-5 top-1/2 size-24 -translate-y-1/2 opacity-20',
} as const
