export const digitalBankingStyles = {
  grid: 'grid items-center gap-12 lg:grid-cols-12 lg:gap-10',
  text: 'lg:col-span-5',
  title: 'text-[26px] leading-[1.35] font-semibold md:text-[32px]',
  description: 'mt-4 max-w-xl text-[17px] leading-[1.8] text-body md:text-lg',
  features: 'mt-8 space-y-4',
  feature: 'flex items-start gap-3 text-ink',
  check: 'mt-1 inline-flex size-6 shrink-0 items-center justify-center rounded-md bg-sand-100 text-brand-600',
  actions: 'mt-10 flex flex-wrap items-center gap-x-5 gap-y-3',
  storeNote: 'text-sm text-muted',
  visual: 'relative lg:col-span-7',
  photo: 'overflow-hidden rounded-xl',
  image: 'aspect-16/10 w-full object-cover',
  caption: 'mt-3 flex flex-wrap items-baseline justify-between gap-x-4 text-[13px] text-muted',
  phone: 'mt-6 lg:absolute lg:end-8 lg:-bottom-6 lg:mt-0',
} as const
