import {
  BankIcon,
  BellIcon,
  BriefcaseIcon,
  BuildingsIcon,
  CalculatorIcon,
  CalendarBlankIcon,
  CertificateIcon,
  ChartLineUpIcon,
  ChartPieIcon,
  ChatCircleTextIcon,
  CheckCircleIcon,
  CheckIcon,
  ClockIcon,
  CoinsIcon,
  CreditCardIcon,
  DeviceMobileIcon,
  EnvelopeSimpleIcon,
  EyeIcon,
  FactoryIcon,
  FileTextIcon,
  FingerprintIcon,
  GlobeIcon,
  GraduationCapIcon,
  HandCoinsIcon,
  HandshakeIcon,
  HeadsetIcon,
  IdentificationCardIcon,
  LightbulbIcon,
  LockKeyIcon,
  MapPinIcon,
  MoneyIcon,
  PackageIcon,
  PasswordIcon,
  PercentIcon,
  PhoneIcon,
  PiggyBankIcon,
  PlantIcon,
  ProhibitIcon,
  ReceiptIcon,
  ScalesIcon,
  SealCheckIcon,
  ShieldCheckIcon,
  ShieldWarningIcon,
  StackIcon,
  StorefrontIcon,
  TargetIcon,
  TimerIcon,
  TractorIcon,
  ArrowsLeftRightIcon,
  TruckIcon,
  UsersIcon,
  UsersThreeIcon,
  VaultIcon,
  WalletIcon,
  WarningIcon,
  WifiHighIcon,
  WrenchIcon,
  type Icon,
} from '@phosphor-icons/react'
import type { IconName } from '@/shared/types'

export const ICON_REGISTRY: Record<IconName, Icon> = {
  bank: BankIcon,
  bell: BellIcon,
  briefcase: BriefcaseIcon,
  buildings: BuildingsIcon,
  calculator: CalculatorIcon,
  calendar: CalendarBlankIcon,
  certificate: CertificateIcon,
  chartPie: ChartPieIcon,
  chartUp: ChartLineUpIcon,
  chat: ChatCircleTextIcon,
  check: CheckIcon,
  checkCircle: CheckCircleIcon,
  clock: ClockIcon,
  coins: CoinsIcon,
  creditCard: CreditCardIcon,
  envelope: EnvelopeSimpleIcon,
  eye: EyeIcon,
  factory: FactoryIcon,
  fileText: FileTextIcon,
  fingerprint: FingerprintIcon,
  globe: GlobeIcon,
  graduation: GraduationCapIcon,
  handCoins: HandCoinsIcon,
  handshake: HandshakeIcon,
  headset: HeadsetIcon,
  idCard: IdentificationCardIcon,
  lightbulb: LightbulbIcon,
  lock: LockKeyIcon,
  mapPin: MapPinIcon,
  mobile: DeviceMobileIcon,
  money: MoneyIcon,
  package: PackageIcon,
  password: PasswordIcon,
  percent: PercentIcon,
  phone: PhoneIcon,
  piggyBank: PiggyBankIcon,
  plant: PlantIcon,
  prohibit: ProhibitIcon,
  receipt: ReceiptIcon,
  scales: ScalesIcon,
  seal: SealCheckIcon,
  shieldCheck: ShieldCheckIcon,
  shieldWarning: ShieldWarningIcon,
  stack: StackIcon,
  storefront: StorefrontIcon,
  target: TargetIcon,
  timer: TimerIcon,
  tractor: TractorIcon,
  transfer: ArrowsLeftRightIcon,
  truck: TruckIcon,
  users: UsersIcon,
  usersThree: UsersThreeIcon,
  vault: VaultIcon,
  wallet: WalletIcon,
  warning: WarningIcon,
  wifi: WifiHighIcon,
  wrench: WrenchIcon,
}
